# Generated by Django 4.2 on 2023-04-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_limittime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limittime',
            name='timer',
            field=models.IntegerField(),
        ),
    ]
